resolvers:
  no-color-keywords: 0
  space-before-colon: 0
rules:
  brace-style: '1tbs'
  no-css-comments: 0
  no-important: 0
  no-ids: 0
  space-before-brace: 2
  variable-name-format: 0
  no-color-literals: 0
  class-name-format: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-qualifying-elements: 0
  nesting-depth: 4
  no-vendor-prefixes: 0
  property-sort-order:
    - 2
    -
      order: 'recess'
  leading-zero:
    - 1
    - include: false
  indentation:
    - 2
    -
      size: 4
  zero-unit:
    - 1
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
